[grt]
gtfs_url = "https://www.regionofwaterloo.ca/opendatadownloads/GRT_GTFS.zip"
gtfs_rt_updates_url = "http://webapps.regionofwaterloo.ca/api/grt-routes/api/tripupdates"

[ttc]
gtfs_url = "https://ckan0.cf.opendata.inter.prod-toronto.ca/dataset/7795b45e-e65a-4465-81fc-c36b9dfff169/resource/cfb6b2b8-6191-41e3-bda1-b175c51148cb/download/TTC Routes and Schedules Data.zip"
gtfs_rt_updates_url = "https://bustime.ttc.ca/gtfsrt/trips"